[server]
enableStaticServing = true
port = 5000
sslCertFile = '/etc/ssl/certs/apache-selfsigned.crt'
sslKeyFile = '/etc/ssl/private/apache-selfsigned.key'

[browser]
#serverAddress = '0.0.0.0'
serverAddress = 'rumahharmoni.my.id'
